### ISSUE TITLE
Question About vmq_mqttbench

### ISSUE THREAD

**Issue by VincentNgai86** [erlio/vmq_mqttbench#7] opened 2017-06-19 14:23 UTC
Hi There,

I am using this bench load test my vmq server ,but have little difficult to read the result
can you explain more on below data meaning ?

VMQ Server = AWS M4 Large
Testing Client = AWS T2.small 

MY Cmd to run the test :
./vmq_mqttbench -s ./sample.steps  -h REMOTEServer --print-stats -n 10000 -r 100

1. As i know that i setup 10000 for the parallel connection (concurrent connected client right ?)
As result I got 9980 concurrent connected client ?
I have not miss any of message , because publish == consumed number

not understand the other number means... and may i know -r 100 is means the first second i got 100 client and the second 200 , then 300 until i reach 10000 ?

2. I did tested another round
./vmq_mqttbench -s ./sample.steps  -h REMOTEServer --print-stats -n 15000 -r 100
I got below number  {num_instances,13958},
and then next got
 [<0.14551.0>] instance terminated due to exit {cant_connect,eaddrnotavail}

Is that means my vmq server only capable to accept around 14000 concurrent connected client 

----------------------Below information----------------

[{publish_rate,9980},
 {consume_rate,9980},
 {bytes_out_rate,1759849},
 {bytes_in_rate,1759849},
 {consumed_msgs,4185156},
 {published_msgs,4185156},
 {num_instances,10000},
 {bytes_in,738048145},
 {bytes_out,738954889},
 {n,1028},
 {min,920},
 {max,165490},
 {arithmetic_mean,24527.303501945524},
 {percentile,[{50,5646},
              {75,34688},
              {90,76810},
              {95,114947},
              {99,142577},
              {999,160229}]}]

**Comment by ioolkos** [comment] 2017-06-19 19:54
Hi @VincentNgai86 thanks! ...what is your ephemereal port range on both test client and server? 
do you happen to go beyond that with your nr of connections?

**Comment by VincentNgai86** [comment] 2017-06-20 03:33
Hello @ioolkos  ,

I Enable all tcp 0-65535 between vmq server and test client

and i checked my vernemq.conf 
listener.max_connections = 100000
listener.nr_of_acceptors = 10000
erlang.distribution.port_range.minimum = 6000

i did not config erlang.distribution.port_range.maximum

**Comment by VincentNgai86** [comment] 2017-06-20 08:49
I have done the testing with vmq_mqttbench, I find no matter how i modify the instance type , it only support 10000 stable connection .

Here is my system level config in Ubuntu 16 and provide the testing resullt.

**/etc/sysctl.conf**
kernel.pid_max = 131072
fs.file-max = 131072

**/etc/security/limits.conf** 
* soft nofile 100000
* hard nofile 100000
root soft nofile 100000
root hard nofile 100000

**/proc/sys/net/ipv4/ip_local_port_range**
32768   60999


![screen shot 2017-06-20 at 4 03 23 pm](https://user-images.githubusercontent.com/24584190/27324081-8d88fafc-55d6-11e7-9873-e6be557b6de1.png)


As result you can see i try different setting with e.g haproxy plus 2 same config vmq server, single vmq server test , change instance type...
none of them can , am i doing something wrong ? or some setting is need to modify ?

**Comment by larshesel** [comment] 2017-06-20 09:01
The problem is likely the setup between haproxy and vernemq. If haproxy connects from localhost *to* localhost then you'll end up in port range exhaustion. One way to solve this is to define several localhost interfaces (127.0.0.2, 127.0.0.3,...) and use these between haproxy and vernemq. Then new local IPs can be used by HAproxy as source IPs and they can then connect to different listeners on VerneMQ. Something along the following lines in the haproxy cfg:

```
	server vmq_vmq1 127.0.0.1:1883 source 127.0.1.1 send-proxy-v2 send-proxy-v2-ssl send-proxy-v2-ssl-cn
	server vmq_vmq2 127.0.0.1:1884 source 127.0.1.2 send-proxy-v2 send-proxy-v2-ssl send-proxy-v2-ssl-cn
	server vmq_vmq3 127.0.0.1:1885 source 127.0.1.3 send-proxy-v2 send-proxy-v2-ssl send-proxy-v2-ssl-cn
	server vmq_vmq4 127.0.0.1:1886 source 127.0.1.4 send-proxy-v2 send-proxy-v2-ssl send-proxy-v2-ssl-cn
```

**Comment by VincentNgai86** [comment] 2017-06-20 09:15
Hi @larshesel  
I do have a testing only go directly between Test Client and VMQ Server with 15000 
(The last green one)

**Comment by larshesel** [comment] 2017-06-20 09:22
In any case it's the same issue - port exhaustion in the ephemeral port range - create more ip addresses on your client machine and pass them to `vmq_mqttbench` using the `--src-addr` flag.

**Comment by VincentNgai86** [comment] 2017-06-20 10:35
@larshesel 
Thanks for your ans, Is that i only need to add in Test Client ?

I added another network interface in the Test Client (the one with vmq_mqttbench)

ens3      Link encap:Ethernet  HWaddr 12:17:f5:16:73:ea  
          inet addr:172.32.63.21  Bcast:172.32.63.255  Mask:255.255.240.0
          inet6 addr: fe80::1017:f5ff:fe16:73ea/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:702 errors:0 dropped:0 overruns:0 frame:0
          TX packets:543 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:68348 (68.3 KB)  TX bytes:80068 (80.0 KB)

ens4      Link encap:Ethernet  HWaddr 12:0b:3b:b6:5e:32  
          inet addr:172.32.63.201  Bcast:172.32.63.255  Mask:255.255.240.0
          inet6 addr: fe80::100b:3bff:feb6:5e32/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:716 (716.0 B)  TX bytes:1332 (1.3 KB)


./vmq_mqttbench -s ./sample.steps  --src-addr  "172.32.63.21,172.32.63.201" -h 172.32.58.185  --print-stats -n 15000 -r 1000 

But result i got num_instances = 7468 

[{publish_rate,7459},
 {consume_rate,7452},
 {bytes_out_rate,1315547},
 {bytes_in_rate,1314139},
 {consumed_msgs,594757},
 {published_msgs,594771},
 {num_instances,7468},
 {bytes_in,104916048},
 {bytes_out,105595895},
 {n,1028},
 {min,287},
 {max,10311},
 {arithmetic_mean,1780.5311284046693},
 {percentile,[{50,1108},{75,2487},{90,3996},{95,4685},{99,7920},{999,10190}]}]

**Comment by larshesel** [comment] 2017-06-20 10:50
Is the new interface reachable from the server? It seems suspiciously close to 15000/2 number of connections that succeeded - so my guess is you have an issue with the new interface.

In any case I don't think there are any issues with `vmq_mqttbench` here but rather an issue with your setup, so I'll close this issue.

**Closed as completed by larshesel** 2017-06-20 10:50 UTC
